### PR TITLE
Refactoring of the 'lotus generate' CLI

### PR DESCRIPTION
**Pull request by pascalbetz**
* A class per generate subcommand
* Generators are not directly dependent on Thor anymore (though they still use Thor to process templates)
* Extracted Thor/CLI handling into own file to make cli.rb more readable
* Better testability

Relevant Issue: https://github.com/lotus/lotus/issues/297

### CODE REVIEW

**Comment by pascalbetz** [comment]
Looking for feedback, PR is not complete yet, hence created it against my own repo and not lotus/lotus. Some places where i intend to work on are already marked with TODO.

_lotus generate model_ and _lotus generate migration_ are working. The other actions are currently broken.

Before i continue i'd like to get some feedback if you like the direction the code went.

Some comments:

* currently changes are for 'lotus generate' commands but would like to structure ALL commands in the same way (even simple stuff like 'lotus version') to be consistent with the structure
* removed dependency to Thor from generators (Lotus::Commands::Generate::*). Thor is now only used for parsing the command line and generating templates/appending to files
* i split up code in different classes (single concern), but currently 'lotus generate model' is still quite complex. Ideas to simplify?
* tests are split up for each command as well, makes them more readable i think
*

**Comment by joneslee85** [comment]
I love what I am seeing, please pursue, just get a rough version first, we'll talk about simplifying model generator later

**Comment by pascalbetz** [comment]
@joneslee85 please start to review. It's pretty much done.

Some questions are in cli.rb at the top. the "generate action" command needs some more cleanup, but honestly i'd love to hear from jodosha about app vs. container first (because i think app should be removed).

**Comment by joneslee85** [comment]
@pascalbetz can you please create PR?

**Pull request merged**
